CREATE TABLE IF NOT EXISTS public.country(
    id INT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(80) NOT NULL,
    iso2 CHAR(2) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);